export const predefinedIngredients = [
  { emoji: '🥚', name: 'eggs', qty: '12', unit: 'pieces', bought: true },
  { emoji: '🥛', name: 'milk', qty: '1', unit: 'liter', bought: false },
  { emoji: '🍞', name: 'bread', qty: '2', unit: 'loaves', bought: true },
  { emoji: '🧀', name: 'cheese', qty: '200', unit: 'grams', bought: false },
  { emoji: '🍗', name: 'chicken', qty: '500', unit: 'grams', bought: false },
  { emoji: '🥩', name: 'beef', qty: '1', unit: 'kg', bought: false },
  { emoji: '🍚', name: 'rice', qty: '1', unit: 'kg', bought: true },
  { emoji: '🍝', name: 'pasta', qty: '500', unit: 'grams', bought: false },
  { emoji: '🥔', name: 'potatoes', qty: '5', unit: 'pieces', bought: false },
  { emoji: '🥕', name: 'carrots', qty: '4', unit: 'pieces', bought: true },
  { emoji: '🧅', name: 'onions', qty: '3', unit: 'pieces', bought: false },
  { emoji: '🧄', name: 'garlic', qty: '6', unit: 'cloves', bought: false },
  { emoji: '🍅', name: 'tomatoes', qty: '4', unit: 'pieces', bought: true },
  { emoji: '🌽', name: 'corn', qty: '2', unit: 'cobs', bought: false },
  { emoji: '🥬', name: 'lettuce', qty: '1', unit: 'head', bought: false },
  { emoji: '🥒', name: 'cucumber', qty: '2', unit: 'pieces', bought: true },
  {
    emoji: '🌶️',
    name: 'chili pepper',
    qty: '3',
    unit: 'pieces',
    bought: false,
  },
  { emoji: '🍋', name: 'lemon', qty: '2', unit: 'pieces', bought: false },
  { emoji: '🧂', name: 'salt', qty: '1', unit: 'tbsp', bought: false },
  { emoji: '🛢️', name: 'olive oil', qty: '100', unit: 'ml', bought: true },
];
